### ISSUE TITLE
Open Link in New Tab

### ISSUE THREAD

**Issue by amanis10** [lookit/lookit-docs#153]
One issue I had while working through the tutorial was that I kept losing my place because I would click on a link and it would open in the tab I was currently in. It wasn't a huge issue because I could right click and "open link in new tab," but I did lose my spot a couple times when I wasn't paying attention. It would be helpful for the link to automatically open up a new tab.

**Comment by kimberscott** [comment]
Thanks, that's a great point! All external links now open in new tabs. (Via Javascript as described in https://stackoverflow.com/a/62742435. Technically, yes, this is "supposed" to be left to the user - but in this case we have a decent idea of what our users want to have happen esp. in the tutorial.)
