### ISSUE TITLE
Institutional Agreement Instructions

### ISSUE THREAD

**Issue by candicerubie** [lookit/lookit-docs#200]
I was trying to find out about how to submit an institutional agreement to add a new PI and lab for an institution that already has an access agreement set up, but I noticed that the instructions cut off mid sentence. 

https://lookit.readthedocs.io/en/develop/community-irb-and-legal-information.html
(Under How to get it signed: "Checking in about an existing agreement also allows you to-")

Thanks!

**Comment by kimberscott** [comment]
Oh no, thanks for catching that! I think I remember what the idea was - updated that dangling sentence to read "If there were any modifications to the standard agreement made for your institution, you'll be able to just use the modified form instead of having to re-negotiate the same changes."
