### ISSUE TITLE
Update out-of-date information on Features page

### ISSUE THREAD

**Issue by mekline** [lookit/lookit-docs#244]
The following updates are needed for https://lookit.readthedocs.io/en/develop/features.html:

(1) Under Common Resources, "A time-tested approach to consenting families online that has been approved by review boards at 10+ institutions." --> is now actually 50+ institutions!

(2) Under Limitations: Please remove these bullet points, as we now support these kinds of studies!!

* Interactive, synchronous studies where an experimenter talks with the family over audio or video chat, or where participants interact with each other. Lookit does not yet have these capabilities.

* Studies you have already implemented for adults and want to run with older children and teens as well. (You could run a study like this on Lookit, but if you already have a robust setup for collecting data from adults, it will probably be easier to stick with that!)

**Comment by ec6wellesley** [comment]
@mekline How do I go from my branch to develop? When I input "git checkout -develop", it gives me an error of some sort.
ElizabethsAir2:lookit-docs elizabethchoi$ git branch --show-current
ec_231_changes
ElizabethsAir2:lookit-docs elizabethchoi$ git checkout -develop
error: unknown switch `e'
usage: git checkout [<options>] <branch>
   or: git checkout [<options>] [<branch>] -- <file>...

    -b <branch>           create and checkout a new branch
    -B <branch>           create/reset and checkout a branch
    -l                    create reflog for new branch
    --guess               second guess 'git checkout <no-such-branch>' (default)
    --overlay             use overlay mode (default)
    -q, --quiet           suppress progress reporting
    --recurse-submodules[=<checkout>]
                          control recursive updating of submodules
    --progress            force progress reporting
    -m, --merge           perform a 3-way merge with the new branch
    --conflict <style>    conflict style (merge or diff3)
    -d, --detach          detach HEAD at named commit
    -t, --track           set upstream info for new branch
    -f, --force           force checkout (throw away local modifications)
    --orphan <new-branch>
                          new unparented branch
    --overwrite-ignore    update ignored files (default)
    --ignore-other-worktrees
                          do not check if another worktree is holding the given ref
    -2, --ours            checkout our version for unmerged files
    -3, --theirs          checkout their version for unmerged files
    -p, --patch           select hunks interactively
    --ignore-skip-worktree-bits
                          do not limit pathspecs to sparse entries only

ElizabethsAir2:lookit-docs elizabethchoi$

**Comment by ec6wellesley** [comment]
@mekline I think I figured it out! I took out the hyphen before develop.
