### ISSUE TITLE
Screen Resources page for dead links

### ISSUE THREAD

**Issue by mekline** [lookit/lookit-docs#246]
Need to review this page (https://lookit.readthedocs.io/en/develop/other-learning-materials.html) for dead links and out-of-date resources.  

For any dead links discovered, should do a quick google search for a replacement link, or add the text "DEAD LINK" in the PR for Melissa to review identify replacement resources.

**Comment by ec6wellesley** [comment]
@mekline I'm not quite sure how you would like me to make a PR when I found a dead link that I can't find a replacement for, such as the following: 

Feel free to fill out the [survey](https://goo.gl/forms/cGpQNPHXSsZmc75W2) collecting info about what people would do with Lookit

[3-year plan](https://docs.google.com/spreadsheets/d/1b2u4NE75IdbNBVRnh6wQgrZmXVPTNlKv-IazUOWUp5Q/edit?usp=sharing)

If you would like I can make edits to the file and create a PR from that?
