### ISSUE TITLE
add docs related to URL query strings for external studies

### ISSUE THREAD

**Issue by becky-gilbert** [lookit/lookit-docs#276]
I don't think the docs mention the fact that URL query parameters are added to external study links, so that researchers can automatically get/record child IDs on their external study platform (Qualtrics, etc.). Please let me know if I've missed this somewhere! If not we should add it.

**Comment by mekline** [comment]
Reminder/comment that there are three cases of "link exit" from Lookit, all of which should ideally work in the same way - 

- The "Exit URL" parameter on an internal study (study redirects there after the end of a study)
- The study link parameter on an external study
- A link manually added to an internal study at the end that participants click on (I may be wrong about whether this case adds query strings though...)  <- This provides similar functionality to the first but I know it's a pattern some researchers use...

**Comment by becky-gilbert** [comment]
Thanks @mekline! I had only been thinking about link parameters for external study types, so this is very helpful 👍
