### ISSUE TITLE
Update study form documentation to match study-eligibility changes

### ISSUE THREAD

**Issue by mekline** [lookit/lookit-docs#278]
We've added the ability to limit study eligibility by previous studies (participated-yes and participated-no), and this occasioned reorganizing the form a little bit to make it conceptually clearer.  We should update the corresponding documentation to match the new order and explain the new fields! 

Relevant docs page: https://lookit.readthedocs.io/en/develop/researchers-set-study-fields.html#

See PR and issue:
https://github.com/lookit/lookit-api/pull/1047
https://github.com/lookit/lookit-api/issues/625

**Comment by becky-gilbert** [comment]
Yes, this issue was handled by #288 and the changes are now live: https://lookit.readthedocs.io/en/develop/researchers-set-study-fields.html
