### ISSUE TITLE
UPDATE, STRUCTURE - Update study details pages for new split form 

### ISSUE THREAD

**Issue by mekline** [lookit/lookit-docs#327]
See https://github.com/lookit/lookit-api/pull/1244

**Comment by becky-gilbert** [comment]
Update: this was partially completed here: https://github.com/lookit/lookit-docs/pull/437
There are now separate docs pages for the new split form ("Using CHS" -> "Study Details" and "Study Design"). 

However, these two forms might still be referenced elsewhere in the docs as a single "Study create/edit" page. And the screenshots on these pages are missing/wrong.
