### ISSUE TITLE
STRUCTURE - Disappearing tabs as of 10/22 morning

### ISSUE THREAD

**Issue by mekline** [lookit/lookit-docs#435]
Possible related to adding the JSPsych docs - on loading https://lookit.readthedocs.io/en/develop/#, everything looks fine.  However, after clicking on the Experiment Runner tab, only that project remains visible, and there's no way to get back to the main docs page. URL is resolved to https://lookit.readthedocs.io/projects/frameplayer/en/latest/, I'm not sure if that was previously the case or not.  But I expect to see two tabs at both of the following screenshots: 

https://lookit.readthedocs.io/en/develop/#

(correct)

<img width="397" alt="Screenshot 2024-10-22 at 12 54 05 PM" src="https://github.com/user-attachments/assets/7c1b9b8b-b81f-4f33-9f6a-350c5e349bbd">

https://lookit.readthedocs.io/projects/frameplayer/en/latest/

(incorrect)

<img width="651" alt="Screenshot 2024-10-22 at 12 54 22 PM" src="https://github.com/user-attachments/assets/85793c29-dbda-4fd9-9136-0ec4af45ce08">

**Comment by becky-gilbert** [comment]
FWIW, I don't think this is a bug that was recently introduced. I often have to go between the main CHS and EFP docs, and I'm always been annoyed that there's no easy way to get back to CHS from EFP (no tabs, and the "home" icon doesn't take me back).

**Comment by becky-gilbert** [comment]
This issue will be easily fixed once we decide on the new layout here: #439

**Comment by becky-gilbert** [comment]
Update: now that we've decided on the navigation tab layout in the main docs, I'm adding this to the EFP and jsPsych docs. The PR for adding this to the EFP docs is here: https://github.com/lookit/ember-lookit-frameplayer/pull/412
