### ISSUE TITLE
Revamping documentation

### ISSUE THREAD

**Issue by robo360** [lookit/lookit-docs#5]
**TL;DR**: Revamping the documentation

**Narrative**
As a developer, I'd like to be able to learn about the workings of the API and set it up quickly. The current documentation does not allow for this, thus the revamping. I want to add new sections before taking out the old ones.

**Acceptance Criteria**
A precise description of how/when this issue will be considered closed, e.g.:

- [ ] Rico sign-off

**Comment by Datamance** [comment]
Moving this to the backlog - I still think it's important, but there's no bandwidth to do this right now.
